export const PET_LIST_REQUEST = 'PET_LIST_REQUEST'
export const PET_LIST_SUCCESS = 'PET_LIST_SUCCESS'
export const PET_LIST_FAIL = 'PET_LIST_FAIL'

export const PET_RESERVE_REQUEST = 'PET_RESERVE_REQUEST'
export const PET_RESERVE_SUCCESS = 'PET_RESERVE_SUCCESS'
export const PET_RESERVE_FAIL = 'PET_RESERVE_FAIL'
