export const PET_LIST_REQUEST = 'PET_LIST_REQUEST'
export const PET_LIST_SUCCESS = 'PET_LIST_SUCCESS'
export const PET_REMOVE_SUCCESS = 'PET_REMOVE_SUCCESS'
export const PET_LIST_FAIL = 'PET_LIST_FAIL'

export const PET_DETAILS_REQUEST = 'PET_DETAILS_REQUEST'
export const PET_DETAILS_SUCCESS = 'PET_DETAILS_SUCCESS'
export const PET_DETAILS_FAIL = 'PET_DETAILS_FAIL'
export const PET_DETAILS_RESET = 'PET_DETAILS_RESET'

export const PET_UPDATE_REQUEST = 'PET_UPDATE_REQUEST'
export const PET_UPDATE_SUCCESS = 'PET_UPDATE_SUCCESS'
export const PET_UPDATE_FAIL = 'PET_UPDATE_FAIL'

export const CREATE_PET_REQUEST = 'CREATE_PET_REQUEST'
export const CREATE_PET_SUCCESS = 'CREATE_PET_SUCCESS'
export const CREATE_PET_FAIL = 'CREATE_PET_FAIL'
export const CREATE_PET_RESET = 'CREATE_PET_RESET'
